version: '3.8'

services:
  php-authentication-demo-ui-native:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-authentication-demo-ui-native-application
    container_name: php-authentication-demo-ui-native-application
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: php-authentication-demo-ui-native-nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "84:80"
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge

