version: '3.8'

services:
  php-authentication-demo-ui-native:
    build: .
    image: php-authentication-demo-ui-native
    container_name: php-authentication-demo-ui-native
    ports:
      - "83:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/nginx.conf 
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
